AWSTemplateFormatVersion: '2010-09-09'
Description: EC2/application template for Sentia Academy
Parameters:
  BastionSubnet:
    Description: Bastion Subnet
    Type: String
  BastionHostSecurityGroup:
    Description: Bastion Security Group
    Type: String
  AutoScalingSecurityGroup:
    Description: Autoscaling Security Group
    Type: String
  LoadBalancerSecurityGroup:
    Description: Load Balancer Security Group
    Type: String
  AutoScalingSubnet:
    Description: AutoScaling Subnet
    Type: String
  AutoScalingPubSubnet:
    Description: Public Autoscaling Subnet
    Type: String
  AutoScalingPub2Subnet:
    Description: Public 2nd Autoscaling Subnet
    Type: String
  AutoScaling2Subnet:
    Description: AutoScaling 2 Subnet
    Type: String
  KeyName:
    Description: Keyname to use
    Type: String
  Ami:
    Description: Selected Ami from SkeletonStack
    Type: String
  Vpc:
    Description: Vpc from Skeleton Stack
    Type: String
  Sizing:
    Description: Sizing
    Type: String
  NotificationEmail:
    Description: E-mail address for autoscaling notifications
    Type: String
  RdsDb:
    Description: Endpoint of Rds
    Type: String
Mappings:
  EnvironmentSize:
    Small:
      "EC2": "t2.micro"
      "DB": "db.t2.micro"
    Medium:
      "EC2": "db.t2.small"
      "DB": "db.t2.small"
    Large:
      "EC2": "db.t2.medium"
      "DB": "db.t2.medium"
Resources:
  LoadBalancer: #spawn a load balancer
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: AppLoadbalancer
      Scheme: internet-facing
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Subnets:
        - !Ref AutoScalingPubSubnet
        - !Ref AutoScalingPub2Subnet
      Type: application
      Tags:
        - Key: Name
          Value: Internet-Facing Application Loadbalancer
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
     DefaultActions:
       - Type: forward
         TargetGroupArn: !Ref ALBTargetGroup
     LoadBalancerArn: !Ref LoadBalancer
     Port: '80'
     Protocol: HTTP
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
     HealthCheckIntervalSeconds: 60
     UnhealthyThresholdCount: 10
     HealthCheckPath: /
     Name: MyTargetGroup
     Port: 80
     Protocol: HTTP
     VpcId: !Ref Vpc
     TargetGroupAttributes:
       - Key: deregistration_delay.timeout_seconds
         Value: 60
  BastionHostLaunchConfig: #create launch config for bastion host
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
        AssociatePublicIpAddress: true
        ImageId: !Ref Ami
        InstanceMonitoring: false
        InstanceType: t2.micro
        KeyName: !Ref KeyName
        PlacementTenancy: default
        SecurityGroups:
          - Ref: BastionHostSecurityGroup
  BastionHostScalingGroup: # create the asg with a bastion host
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName:
          Ref: BastionHostLaunchConfig
      MinSize: '1'
      MaxSize: '1'
      VPCZoneIdentifier:
        - !Ref BastionSubnet
      Tags:
        - Key: Name
          Value: Bastion host
          PropagateAtLaunch: true
  AsgLaunchConfiguration: #create asg launch config
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      IamInstanceProfile: !Ref LogMetricsCloudWatchProfile
      ImageId: !Ref Ami
      InstanceMonitoring: true
      InstanceType:
       !FindInMap [EnvironmentSize, !Ref Sizing, EC2] #find in mappings corresponding ec2 size
      KeyName: !Ref KeyName
      UserData:
        "Fn::Base64":
          !Sub |
           #!/bin/bash
           yum update -y
           yum install -y httpd24 php56 php56-mysqlnd
           service httpd start
           chkconfig httpd on
           usermod -a -G apache ec2-user
           chown -R ec2-user:apache /var/www
           chmod 2775 /var/www
           yum install -y perl-Switch perl-DateTime perl-Sys-Syslog perl-LWP-Protocol-https perl-Digest-SHA unzip
           cd /home/ec2-user
           curl http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip -O
           unzip CloudWatchMonitoringScripts-1.2.1.zip
           rm -rf CloudWatchMonitoringScripts-1.2.1.zip
           chown ec2-user:ec2-user aws-scripts-mon
           echo "*/5 * * * *ec2-user /home/ec2-user/aws-scripts-mon/mon-put-instance-data.pl --mem-util --aggregated --auto-scaling --from-cron" >> /var/spool/cron/ec2-user
           echo "*/5 * * * *ec2-user /home/ec2-user/aws-scripts-mon/mon-put-instance-data.pl --mem-util --from-cron" >> /var/spool/cron/ec2-user
           curl https://s3.amazonaws.com//aws-cloudwatch/downloads/latest/awslogs-agent-setup.py -O
           chmod +x ./awslogs-agent-setup.py
           ./awslogs-agent-setup.py -n -r us-east-2 -c s3://one-sentia-course/logs.conf
           AMI=`curl -s http://169.254.169.254/latest/meta-data/ami-id`
           REGION=`curl -s http://169.254.169.254/latest/dynamic/instance-identity/document|grep region|awk -F\" '{print $4}'|tr -d '\n'`
           AZ=`curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone`
           INSTANCE_ID=`curl -s http://169.254.169.254/latest/meta-data/instance-id`
           PRIVATE_IP=`curl -s http://169.254.169.254/latest/meta-data/local-ipv4`
           INFORMATION_HTML="<html><header><title>Wow-die-wow-bow it works!</title></header><body><table><tr><th>AMI:</th><td>${Ami}</td></tr><tr><th>Region:</th><td>${AWS::Region}</td></tr><tr><th>Rds Endpoint:</th><td>${RdsDb}</td></tr></table><p><b><i>check github.com/sjoerdsantema/nestedstacks</i></b></p></body></html>"
           echo $INFORMATION_HTML > /var/www/html/index.html
      PlacementTenancy: default
      SecurityGroups:
        - !Ref AutoScalingSecurityGroup
  AutoScalingGroup: #spawn auto-scaling group
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref AsgLaunchConfiguration
      MinSize: 2
      MaxSize: 4
      TargetGroupARNs:
        - !Ref ALBTargetGroup
      VPCZoneIdentifier:
        - !Ref AutoScalingSubnet
        - !Ref AutoScaling2Subnet
      NotificationConfigurations: #send an email to sjoerd whenever an instance is launched, terminated or dying
      - TopicARN: !Ref AlertTopic
        NotificationTypes:
          - autoscaling:EC2_INSTANCE_LAUNCH
          - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
          - autoscaling:EC2_INSTANCE_TERMINATE
          - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
      Tags:
        - Key: Name
          Value: Webserver
          PropagateAtLaunch: true
  ScaleUpPolicy: #scaling policy
   Type: AWS::AutoScaling::ScalingPolicy
   Properties:
     AdjustmentType: ChangeInCapacity
     AutoScalingGroupName: !Ref AutoScalingGroup
     Cooldown: '1'
     ScalingAdjustment: '1'
  AlertTopic:
   Type: AWS::SNS::Topic
   Properties:
    Subscription:
      - Endpoint: !Ref NotificationEmail
        Protocol: 'email'
    TopicName: 'FirstBoot'
  CPUAlarmHigh:
   Type: AWS::CloudWatch::Alarm
   Properties:
     EvaluationPeriods: '1'
     Statistic: Average
     Threshold: '10'
     AlarmDescription: Alarm if CPU too high or metric disappears indicating instance is down
     Period: '60'
     AlarmActions:
      - !Ref ScaleUpPolicy
     Namespace: AWS/EC2
     Dimensions:
      - Name: AutoScalingGroup
        Value: !Ref AutoScalingGroup
     ComparisonOperator: GreaterThanThreshold
     MetricName: CPUUtilization
  LogMetricsCloudWatchRole: #create cloudwatch role
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
  LogMetricsCloudWatchPolicy: #create cloudwatch policy
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LogMetricsCloudWatchPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricdata
              - ec2:DescribeTags
              - logs:PutLogEvents
              - logs:DescribeLogStreams
              - logs:DescribeLogGroups
              - logs:CreateLogStreams
              - logs:CreateLogGroup
            Resource: "*"
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: arn:aws:s3:::one-sentia-course/*
      Roles:
        - !Ref LogMetricsCloudWatchRole
  LogMetricsCloudWatchProfile: #link cloudwatch role to profile
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref LogMetricsCloudWatchRole
Outputs:
  BastionHost:
    Description: Bastion created in skeleton
    Value: !Ref BastionHostScalingGroup
  LoadBalancer:
    Description: Endpoint of load balancer
    Value: !GetAtt 'LoadBalancer.DNSName'
