AWSTemplateFormatVersion: '2010-09-09'
Description: Parent Stack with nested stacks for networking, ec2 and app; no database; deployments through CodePipeline en CodeDeploy; commit is parameter
Parameters:
  Repository: #link to repository where application is stored
    Type: String
    Default: "http://github.com/sjoerdsantema/loremipsum"
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: trainingdays
  Sizing: #added so sizing can easily be changed when needed
    Type: String
    Default: "Small"
    AllowedValues:
     - Small
     - Expensive
     - Mega
    Description: Select sizing
  Ami:
    Type: String
    Default: ami-40142d25 #this ami is only available in us-east-2 under this number! consider using mapping instead of hard coding
Resources:
 SkeletonStack:
  Type: AWS::CloudFormation::Stack
  Properties:
    TemplateURL: https://s3-eu-west-1.amazonaws.com/one-sentia-course/CFNTemplates/new-dawn/skeleton.yaml
    TimeoutInMinutes: 60
 AppStack:
  Type: AWS::CloudFormation::Stack
  Properties:
    TemplateURL: https://s3-eu-west-1.amazonaws.com/one-sentia-course/CFNTemplates/new-dawn/app.yaml
    Parameters:
      Repository: !Ref Repository
      BastionSubnet:
        !GetAtt 'SkeletonStack.Outputs.SBastionSubnet'
      BastionHostSecurityGroup:
        !GetAtt 'SkeletonStack.Outputs.SBastionHostSecurityGroup'
      LoadBalancerSecurityGroup:
        !GetAtt 'SkeletonStack.Outputs.SLoadBalancerSecurityGroup'
      AutoScalingSubnet:
        !GetAtt 'SkeletonStack.Outputs.SAutoScalingSubnet'
      AutoScaling2Subnet:
        !GetAtt 'SkeletonStack.Outputs.SAutoScaling2Subnet'
      AutoScalingPubSubnet:
        !GetAtt 'SkeletonStack.Outputs.SAutoScalingPubSubnet'
      AutoScalingPub2Subnet:
        !GetAtt 'SkeletonStack.Outputs.SAutoScalingPub2Subnet'
      AutoScalingSecurityGroup:
        !GetAtt 'SkeletonStack.Outputs.SAutoScalingSecurityGroup'
      KeyName: !Ref KeyName
      Sizing: !Ref Sizing
      Vpc:
        !GetAtt 'SkeletonStack.Outputs.SVPC'
      Ami: !Ref Ami
    TimeoutInMinutes: 60
Outputs:
  SVPC:
   Description: VpcId SkeletonStack
   Value:
    !GetAtt 'SkeletonStack.Outputs.SVPC'
  LoadBalancerEndpoint:
    Description: Endpoint of the load Balancer (http)
    Value:
      !Join ["",['http://',!GetAtt 'AppStack.Outputs.LoadBalancer','/index.html']]
