AWSTemplateFormatVersion: '2010-09-09'
Description: RDS template for Sentia Academy
Parameters:
  DatabaseSubnet:
    Description: 1 of 2 db subnets
    Type: String
  Database2Subnet:
    Description: 2 of 2 db subnets
    Type: String
  Sizing:
    Description: Sizing
    Type: String
  ParDatabasename:
    Description: Name of database
    Type: String
  Databaseuser:
    Description: Name of database user
    Type: String
  Databasepassword:
    Description: Database password
    Type: String
  DatabaseSecurityGroup:
    Description: Id of database security group
    Type: String
Mappings:
  EnvironmentSize:
    Small:
      "EC2": "t2.micro"
      "DB": "db.t2.micro"
    Medium:
      "EC2": "db.t2.small"
      "DB": "db.t2.small"
    Large:
      "EC2": "db.t2.medium"
      "DB": "db.t2.medium"
Resources:
 DataBaseSubnetGroup: #not in skeleton due to limitations in cfn
   Type: "AWS::RDS::DBSubnetGroup"
   Properties:
    DBSubnetGroupDescription: RDS cluster
    DBSubnetGroupName: RDSSUBGROUP
    SubnetIds:
     - !Ref DatabaseSubnet
     - !Ref Database2Subnet
 DBInstance:
  Type: AWS::RDS::DBInstance
  Properties:
   DBName: !Ref ParDatabasename
   Engine: MySQL
   BackupRetentionPeriod: 0
   MultiAZ: true
   MasterUsername: !Ref Databaseuser
   DBInstanceClass:
    !FindInMap [EnvironmentSize, !Ref Sizing, DB] #find in mappings corresponding db size
   AllocatedStorage: 8
   MasterUserPassword: !Ref Databasepassword
   DBSubnetGroupName: !Ref DataBaseSubnetGroup
   VPCSecurityGroups:
    - !Ref DatabaseSecurityGroup
Outputs:
 RdsDb:
   Description: Rds Name
   Value:
    !GetAtt 'DBInstance.Endpoint.Address'
